DROP TABLE IF EXISTS task_category CASCADE;
DROP TABLE IF EXISTS task CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS mandatory CASCADE;
DROP TABLE IF EXISTS app_user CASCADE;
DROP TABLE IF EXISTS user_task CASCADE;